### ISSUE TITLE
Passing data between classes with SWRevealViewController in swift

### ISSUE THREAD

**Issue by ilirvg** [John-Lluch/SWRevealViewController#424]
I am passing this issue from stackoverflow.com so the same question wont be repeated. I have seen that there are many question about SWRevealViewController for using it in swift without answers. But I really hope that someone has figured it out. 
Here is the link of the question: http://stackoverflow.com/questions/30414101/passing-data-between-classes-with-swrevealviewcontroller-in-swift?noredirect=1#comment48914767_30414101

**Comment by John-Lluch** [comment]
My guess is that this is not replied any more because this was already answered. Not particularly on Swift but on Objective-C. Essentially, the most accepted advice is to code by using the MVC pattern and principles, and consequently to avoid passing information directly between controllers. I would recommend you to pick a good book on Cocoa and Objective-C iOS Design Patterns, then apply the same on Swift.  The following tutorial is a good starting point :  http://www.raywenderlich.com/46988/ios-design-patterns. Once you interiorize this kind of programming everything becomes a lot easier. I hope this helps to get your answer yourself.

**Comment by ilirvg** [comment]
Thank you I have figure it out using singletons
