### ISSUE TITLE
Problem with the left reveal menu when using swipe gesture

### ISSUE THREAD

**Issue by DennisDreissen** [John-Lluch/SWRevealViewController#488]
I have a problem with my menu using the swipe gesture. Whenever I use the swipe action to reveal the menu before using the button first, the menu view looks really weird. I have screenshots attached below. The issue disappears whenever the reveal menu is activated by pressing the button first.

<b>This is how it looks when using the swipe action before using the button first.</b>
![Wrong](http://puu.sh/kQiAw/a0f5c2cbc2.png)

<b>This is how it looks when pressing the button or swiping after the button has been used at least once.</b>
![Good](http://puu.sh/kQixV/b8c94f7ff4.png)

Does anyone else have this issue and how did you resolve it? Or what could be the issue here?

I'm using this code in all my view controllers to implement the SWRevealController:

```
if self.revealViewController() != nil {
     menuButton.target = self.revealViewController()
     menuButton.action = "revealToggle:"
     self.view.addGestureRecognizer(self.revealViewController().panGestureRecognizer())
}
```

**Comment by ejimenez93** [comment]
+1-ing this post.

Same issue occurs for me. Scenario:
* Load up my app
* Swipe to the left and my alignment is similar to the first screenshot above (everything is far left)
* Tap on the nav button to open up the slider and the alignment is perfect -- responding to the constraints I've set up
* From here on out, the menu looks like screenshot 2 (even if you swipe instead of tapping on the button) until the app is restarted
* Once the app is restarted (after closing it out entirely) same scenario occurs

Would love to see the solution for this.

**Comment by ejimenez93** [comment]
@DennisDreissen I think I might have found a solution. Add this to your block of code from above, right underneath the panGestureRecognizer:

<code>self.revealViewController().rearViewRevealDisplacement = 0</code>

This seems to have fixed it for me

**Comment by DennisDreissen** [comment]
@ejimenez93 Works great! Thanks a lot. :-) :+1:
