### ISSUE TITLE
self.revealViewController is nil when running a XCTest

### ISSUE THREAD

**Issue by penaeric** [John-Lluch/SWRevealViewController#89]
I'm writing XCTests to test something not related to SWRevealViewController. 
When my main view loads I add a GestureRecognizer and it works just fine, except when the simulator is running a test.
When the simulator is running a test, self.revealViewController is nil so I have to do something like:

```
    if (self.revealViewController) {
        [self.navigationController.navigationBar addGestureRecognizer:self.revealViewController.panGestureRecognizer];
    }
```

It's probably not a good idea to do this, as I would expect the gesture recognizer to be (always) added, because I expect self to have a revealViewController property.
I suspect this is not a problem with this library, but the way the simulator runs the app when running a XCTest.
If this is the case, I'd like to file a radar as we'd expect to have the same functionality when running the app wether we're running a test or not, but I have to be more or less certain of this being a problem with XCode/simulator.

Has anyone seen this behavior? 
Is there a reason why self.revealViewController is nil when running a XCTest?

**Comment by Hyojjung** [comment]
I have same problem. I want to know answer.

**Comment by MartinDevi** [comment]
I also still have this problem. The crash is indeed due to the fact that self.revealViewController is nil while running unit tests. The reason for this can be found in the getter, because `[parent isKindOfClass:revealClass]` always returns false. This only happens when the SWRevealViewController is integrated into the project via CocoaPods (or in some other way as an external library), and the issue is linked to the way the project manages classes in unit tests (see [StackOverflow](http://stackoverflow.com/questions/5755289/iskindofclass-returns-false-negative-in-unit-test-bundle) for a related problem). I have no idea how to fix this.

If I'm not mistaken, it's therefore currently impossible to run unit test on an application where SWRevealViewController is added via CocoaPods and where the starting view controller is a SWRevealViewControlle because the app crashes immediately.
